/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DevComponentsRouteImport } from './routes/dev/components'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as JournalEntryIdRouteImport } from './routes/journal/$entryId'
import { Route as JournalNewRouteImport } from './routes/journal/new'
import { Route as JournalEntryIdEditRouteImport } from './routes/journal/$entryId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/dev/components',
  path: '/dev/components',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalEntryIdRoute = JournalEntryIdRouteImport.update({
  id: '/journal/$entryId',
  path: '/journal/$entryId',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalNewRoute = JournalNewRouteImport.update({
  id: '/journal/new',
  path: '/journal/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalEntryIdEditRoute = JournalEntryIdEditRouteImport.update({
  id: '/journal/$entryId_/edit',
  path: '/journal/$entryId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dev/components': typeof DevComponentsRoute
  '/journal/$entryId': typeof JournalEntryIdRoute
  '/journal/new': typeof JournalNewRoute
  '/journal/': typeof JournalIndexRoute
  '/journal/$entryId/edit': typeof JournalEntryIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dev/components': typeof DevComponentsRoute
  '/journal/$entryId': typeof JournalEntryIdRoute
  '/journal/new': typeof JournalNewRoute
  '/journal': typeof JournalIndexRoute
  '/journal/$entryId/edit': typeof JournalEntryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dev/components': typeof DevComponentsRoute
  '/journal/$entryId': typeof JournalEntryIdRoute
  '/journal/new': typeof JournalNewRoute
  '/journal/': typeof JournalIndexRoute
  '/journal/$entryId_/edit': typeof JournalEntryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dev/components'
    | '/journal/$entryId'
    | '/journal/new'
    | '/journal/'
    | '/journal/$entryId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dev/components'
    | '/journal/$entryId'
    | '/journal/new'
    | '/journal'
    | '/journal/$entryId/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/dev/components'
    | '/journal/$entryId'
    | '/journal/new'
    | '/journal/'
    | '/journal/$entryId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  DevComponentsRoute: typeof DevComponentsRoute
  JournalEntryIdRoute: typeof JournalEntryIdRoute
  JournalNewRoute: typeof JournalNewRoute
  JournalIndexRoute: typeof JournalIndexRoute
  JournalEntryIdEditRoute: typeof JournalEntryIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/components': {
      id: '/dev/components'
      path: '/dev/components'
      fullPath: '/dev/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$entryId': {
      id: '/journal/$entryId'
      path: '/journal/$entryId'
      fullPath: '/journal/$entryId'
      preLoaderRoute: typeof JournalEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/new': {
      id: '/journal/new'
      path: '/journal/new'
      fullPath: '/journal/new'
      preLoaderRoute: typeof JournalNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$entryId_/edit': {
      id: '/journal/$entryId_/edit'
      path: '/journal/$entryId/edit'
      fullPath: '/journal/$entryId/edit'
      preLoaderRoute: typeof JournalEntryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  DevComponentsRoute: DevComponentsRoute,
  JournalEntryIdRoute: JournalEntryIdRoute,
  JournalNewRoute: JournalNewRoute,
  JournalIndexRoute: JournalIndexRoute,
  JournalEntryIdEditRoute: JournalEntryIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
