export const endpoints = {
  health: '/health',
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    logout: '/auth/logout',
    me: '/auth/me',
  },
  journal: {
    entries: '/journal/entries',
    entry: (id: number) => `/journal/entries/${id}`,
    entryByDate: (date: string) => `/journal/entries/by-date/${date}`,
    entriesByRange: '/journal/entries/by-range',
    summary: '/journal/entries/summary',
  },
  dreams: '/dreams',
  dream: (id: number) => `/dreams/${id}`,
  dreamAnchors: (id: number) => `/dreams/${id}/anchors`,
  dreamAnalysisPasses: (id: number) => `/dreams/${id}/analysis-passes`,
  anchor: (id: number) => `/anchors/${id}`,
  anchorEmotionalBeats: (id: number) => `/anchors/${id}/emotional-beats`,
  anchorSymbols: (id: number) => `/anchors/${id}/symbols`,
  emotionalBeat: (id: number) => `/emotional-beats/${id}`,
  symbols: '/symbols',
  symbolAttachment: (id: number) => `/symbol-attachments/${id}`,
  symbolAttachmentAssociations: (id: number) => `/symbol-attachments/${id}/associations`,
  association: (id: number) => `/associations/${id}`,
} as const;
